# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokemonBook
  pod 'Moya/RxSwift'
  pod 'SwiftyJSON'
  pod 'SwiftJWT'
  pod 'KeychainSwift'
  pod 'RxRelay'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'lottie-ios'

  target 'PokemonBookTests' do
  inherit! :complete
  pod 'RxTest'
  pod 'RxBlocking'
 end
end
